@apiUrl = http://172.17.0.2/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmZkODZlMTkzOGNiZDAzZTJmMTcxNmYiLCJpYXQiOjE2MTA0NzA0MTJ9.JlXiKg2tSYhvvFLGDv2U76lbbaZkM9SyvXQgN7a-B24
@refreshToken = ...

GET {{apiUrl}}/users
Content-Type: application/json
authorization: {{accessToken}}

###
POST {{apiUrl}}/users
Content-Type: application/json

{
  "name": "Oleksandr",
  "email": "s.52@ukr.net",
  "password": "123456qW!"
}


### 
POST {{apiUrl}}/auth
Content-Type: application/json

{
  "email": "s.52@ukr.net",
  "password": "123456qW!"
}